import React,{useEffect,useMemo,useState} from 'react';
import {Eye,EyeOff,KeyRound,LogOut,Mail,ShieldCheck,UserRound,X,CheckCircle2} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './AccountCenter.css';

const initials=(name,email)=>String(name||email||'U').split(/\s+|@/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'U';

export default function AccountCenter({open,onClose,user,privacy,onPrivacyChange}){
 const currentName=String(user?.user_metadata?.full_name||user?.user_metadata?.name||'').trim();
 const[name,setName]=useState(currentName),[savingProfile,setSavingProfile]=useState(false),[savingPassword,setSavingPassword]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(open)setName(currentName)},[open,currentName]);
 const joined=useMemo(()=>user?.created_at?new Date(user.created_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}):'—',[user?.created_at]);
 if(!open||!user)return null;
 async function saveProfile(e){e.preventDefault();setError('');setMessage('');setSavingProfile(true);const clean=name.trim();const{error}=await supabase.auth.updateUser({data:{...user.user_metadata,full_name:clean}});setSavingProfile(false);if(error){setError(error.message);return}setMessage('Perfil atualizado.');}
 async function savePassword(e){e.preventDefault();setError('');setMessage('');const f=new FormData(e.currentTarget),password=String(f.get('password')||''),confirm=String(f.get('confirm')||'');if(password.length<6){setError('A senha precisa ter pelo menos 6 caracteres.');return}if(password!==confirm){setError('As senhas não são iguais.');return}setSavingPassword(true);const{error}=await supabase.auth.updateUser({password});setSavingPassword(false);if(error){setError(error.message);return}e.currentTarget.reset();setMessage('Senha alterada com sucesso.');}
 return <div className="account-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="account-center"><div className="account-head"><div><span>CONTA 3.0</span><h2>Central da conta</h2><p>Perfil, segurança e privacidade em um só lugar.</p></div><button onClick={onClose} aria-label="Fechar"><X size={18}/></button></div><div className="account-identity"><div className="account-avatar">{initials(name,user.email)}</div><div><b>{name.trim()||'Seu perfil'}</b><span>{user.email}</span><small>Conta criada em {joined}</small></div><ShieldCheck size={19}/></div>{(message||error)&&<div className={`account-status ${error?'is-error':''}`}>{error?<ShieldCheck size={15}/>:<CheckCircle2 size={15}/>}<span>{error||message}</span></div>}<section className="account-section"><div className="account-section-title"><UserRound size={16}/><div><b>Perfil</b><span>Como você aparece dentro do app.</span></div></div><form onSubmit={saveProfile}><label>Nome</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/><label>E-mail</label><div className="account-readonly"><Mail size={15}/><span>{user.email}</span></div><button className="account-primary" disabled={savingProfile}>{savingProfile?'Salvando...':'Salvar perfil'}</button></form></section><section className="account-section"><div className="account-section-title"><ShieldCheck size={16}/><div><b>Privacidade</b><span>Oculta valores sensíveis sem sair da sua conta.</span></div></div><button className={`privacy-switch ${privacy?'active':''}`} onClick={()=>onPrivacyChange(!privacy)}><div>{privacy?<EyeOff size={17}/>:<Eye size={17}/>}<span><b>Modo privacidade</b><small>{privacy?'Valores ocultos':'Valores visíveis'}</small></span></div><i/></button></section><section className="account-section"><div className="account-section-title"><KeyRound size={16}/><div><b>Segurança</b><span>Altere sua senha de acesso.</span></div></div><form onSubmit={savePassword}><label>Nova senha</label><input name="password" type="password" minLength="6" placeholder="Mínimo de 6 caracteres" required/><label>Confirmar senha</label><input name="confirm" type="password" minLength="6" placeholder="Digite novamente" required/><button className="account-primary" disabled={savingPassword}>{savingPassword?'Alterando...':'Alterar senha'}</button></form></section><button className="account-signout" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sair da conta</button></aside></div>;
}
