import React,{useEffect,useMemo,useState} from 'react';
import {ShieldCheck,Users,ReceiptText,UserPlus,RefreshCw,Crown,Shield,UserRound,CheckCircle2,AlertTriangle,Wallet,Eye,Power,PowerOff,Activity,X,Trash2} from 'lucide-react';
import './AdminPanel.css';
const date=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const actionLabel={create_user:'Usuário criado',set_role:'Permissão alterada',disable_user:'Usuário bloqueado',enable_user:'Usuário reativado',delete_user:'Usuário excluído'};

export default function AdminPanel({session}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[deleteConfirm,setDeleteConfirm]=useState(''),[tab,setTab]=useState('users');
 async function request(body){let r;try{r=await fetch('/api/admin',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined})}catch{throw new Error('Não foi possível conectar à API administrativa. Verifique o deploy do Vercel.')}const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{throw new Error(`A API administrativa respondeu de forma inválida (${r.status}). Faça um novo deploy do Vercel.`)}if(!r.ok||!j.ok)throw new Error(j.error||`Falha no painel administrativo (${r.status}).`);return j}
 async function load(){setLoading(true);setError('');try{const j=await request();setData(j.data);if(selected)setSelected(j.data.users.find(u=>u.id===selected.id)||null)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function createUser(e){e.preventDefault();const form=e.currentTarget;setSaving(true);setError('');setSuccess('');const f=new FormData(form);try{const email=String(f.get('email')||'').trim();await request({action:'create-user',email,password:f.get('password'),makeAdmin:f.get('makeAdmin')==='on'});form.reset();setSuccess(`Conta ${email} criada com sucesso e já confirmada.`);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function act(body,message){setSaving(true);setError('');setSuccess('');try{await request(body);if(message)setSuccess(message);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 function openDelete(user){if(data?.actorRole!=='owner'){setError('A exclusão de usuários precisa ser confirmada pelo proprietário.');return}setDeleteTarget(user);setDeleteConfirm('')}
 async function removeUser(){if(!deleteTarget)return;const email=deleteTarget.email;setSaving(true);setError('');setSuccess('');try{await request({action:'delete-user',userId:deleteTarget.id,confirmEmail:deleteConfirm});setDeleteTarget(null);setDeleteConfirm('');setSelected(null);setSuccess(`Conta ${email} excluída com confirmação do proprietário.`);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const users=useMemo(()=>{const q=query.toLowerCase().trim();return(data?.users||[]).filter(u=>!q||String(u.email||'').toLowerCase().includes(q)||u.role.includes(q))},[data,query]);
 if(loading&&!data)return <section className="admin-shell"><div className="admin-loading"><RefreshCw className="spin" size={22}/> Carregando painel administrativo...</div></section>;
 return <section className="admin-shell">
  <div className="admin-hero"><div><span><ShieldCheck size={14}/> ADMIN CONTROL 2.3</span><h2>Painel administrativo</h2><p>Usuários, atividade, métricas financeiras e trilha de auditoria em um só lugar.</p></div><div className="admin-role"><Crown size={16}/><span>Seu nível</span><b>{data?.actorRole==='owner'?'Proprietário':'Administrador'}</b></div></div>
  {error&&<div className="admin-error"><AlertTriangle size={16}/>{error}</div>}{success&&<div className="admin-success"><CheckCircle2 size={16}/>{success}</div>}
  <div className="admin-stats"><article><Users size={18}/><span>Usuários</span><strong>{data?.stats?.users||0}</strong></article><article><Shield size={18}/><span>Admins</span><strong>{data?.stats?.admins||0}</strong></article><article><ReceiptText size={18}/><span>Lançamentos</span><strong>{data?.stats?.expenses||0}</strong></article><article><Wallet size={18}/><span>Volume registrado</span><strong>{money(data?.stats?.totalSpent)}</strong></article></div>
  <div className="admin-switch"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><Users size={15}/> Usuários</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}><Activity size={15}/> Auditoria</button></div>
  {tab==='users'?<div className="admin-grid"><article className="panel admin-create"><div className="admin-section-head"><div><span>NOVO ACESSO</span><h3>Adicionar usuário</h3></div><UserPlus size={20}/></div><form onSubmit={createUser}><label>E-mail</label><input name="email" type="email" required placeholder="usuario@email.com"/><label>Senha inicial</label><input name="password" type="password" minLength="6" required/><label className="admin-check"><input name="makeAdmin" type="checkbox"/><span><b>Criar como administrador</b><small>Terá acesso ao painel administrativo.</small></span></label><button className="primary" disabled={saving}>{saving?'Criando conta...':'Criar usuário'}</button><small className="admin-create-note">A conta é criada pelo servidor e já fica com o e-mail confirmado.</small></form></article><article className="panel admin-users"><div className="admin-section-head"><div><span>ACESSOS</span><h3>Usuários cadastrados</h3></div><button className="admin-refresh" onClick={load}><RefreshCw size={15}/></button></div><input className="admin-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por e-mail ou função..."/><div className="admin-user-list">{users.map(u=><div className="admin-user" key={u.id}><div className={`admin-avatar role-${u.role}`}>{u.role==='owner'?<Crown size={16}/>:u.role==='admin'?<Shield size={16}/>:<UserRound size={16}/>}</div><div className="admin-user-main"><b>{u.email||'Sem e-mail'}</b><span>{u.metrics.expenses} lançamentos • {money(u.metrics.totalSpent)} • {u.metrics.cards} cartões</span></div><div className={`admin-badge role-${u.role}`}>{u.role==='owner'?'OWNER':u.role==='admin'?'ADMIN':'USUÁRIO'}</div><button className="admin-view" onClick={()=>setSelected(u)}><Eye size={14}/> Detalhes</button></div>)}{!users.length&&<div className="admin-empty">Nenhum usuário encontrado.</div>}</div></article></div>:<article className="panel admin-audit"><div className="admin-section-head"><div><span>SEGURANÇA</span><h3>Trilha de auditoria</h3></div><Activity size={20}/></div><div className="audit-list">{(data?.audit||[]).map(log=><div className="audit-row" key={log.id}><div className="audit-icon"><Activity size={14}/></div><div><b>{actionLabel[log.action]||log.action}</b><span>{log.actor_email} → {log.target_email||'—'}</span></div><time>{date(log.created_at)}</time></div>)}{!data?.audit?.length&&<div className="admin-empty">Nenhuma ação registrada ainda.</div>}</div></article>}
  {selected&&<div className="admin-detail-bg" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="admin-detail"><button className="admin-detail-close" onClick={()=>setSelected(null)}><X size={18}/></button><div className={`admin-detail-avatar role-${selected.role}`}>{selected.role==='owner'?<Crown/>:selected.role==='admin'?<Shield/>:<UserRound/>}</div><span className="admin-detail-kicker">PERFIL DO USUÁRIO</span><h3>{selected.email}</h3><p>Criado em {date(selected.created_at)}<br/>Último acesso {date(selected.last_sign_in_at)}</p><div className="admin-detail-metrics"><div><span>Gastos</span><b>{selected.metrics.expenses}</b></div><div><span>Total</span><b>{money(selected.metrics.totalSpent)}</b></div><div><span>Cartões</span><b>{selected.metrics.cards}</b></div><div><span>Rendas registradas</span><b>{money(selected.metrics.income)}</b></div></div><div className="admin-detail-actions">{selected.role!=='owner'?<><button className="admin-action-role" disabled={saving} onClick={()=>act({action:'set-role',userId:selected.id,role:selected.role==='admin'?'user':'admin'},selected.role==='admin'?'Acesso de administrador removido.':'Usuário promovido a administrador.')}><Shield size={15}/>{selected.role==='admin'?'Remover admin':'Tornar admin'}</button><button className={`admin-action-block ${selected.banned_until?'enable':''}`} disabled={saving} onClick={()=>act({action:'set-access',userId:selected.id,disabled:!selected.banned_until},selected.banned_until?'Usuário reativado.':'Usuário bloqueado.')} >{selected.banned_until?<><Power size={15}/> Reativar usuário</>:<><PowerOff size={15}/> Bloquear usuário</>}</button><button className="admin-action-delete" disabled={saving||data?.actorRole!=='owner'} onClick={()=>openDelete(selected)} title={data?.actorRole==='owner'?'Excluir usuário':'Somente o proprietário pode excluir usuários'}><Trash2 size={15}/> {data?.actorRole==='owner'?'Excluir usuário':'Exclusão exige owner'}</button></>:<span className="admin-protected"><CheckCircle2 size={14}/> Conta proprietária protegida</span>}</div></aside></div>}
  {deleteTarget&&<div className="admin-delete-bg" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setDeleteTarget(null)}><section className="admin-delete-confirm"><div className="admin-delete-icon"><Trash2 size={20}/></div><span>CONFIRMAÇÃO DO PROPRIETÁRIO</span><h3>Excluir usuário permanentemente?</h3><p>Esta ação remove a conta <b>{deleteTarget.email}</b> do Supabase Auth e pode apagar dados vinculados. Não pode ser desfeita.</p><label>Digite exatamente o e-mail para confirmar</label><input value={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.value)} placeholder={deleteTarget.email}/><div><button className="secondary" disabled={saving} onClick={()=>{setDeleteTarget(null);setDeleteConfirm('')}}>Cancelar</button><button className="admin-delete-final" disabled={saving||deleteConfirm.trim().toLowerCase()!==String(deleteTarget.email||'').trim().toLowerCase()} onClick={removeUser}>{saving?'Excluindo...':'Confirmar exclusão'}</button></div></section></div>}
 </section>;
}
