import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,CalendarClock,CreditCard,Repeat,ShieldCheck,Sparkles,TrendingDown,TrendingUp,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import CalcInfo from './CalcInfo';
import './FinancialForecast.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const clamp=(v,min,max)=>Math.min(Math.max(v,min),max);
const monthIndex=(y,m)=>y*12+(m-1);
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,' ' ).replace(/\s+/g,' ').trim();
const sameAmount=(a,b)=>Math.abs(Number(a||0)-Number(b||0))<0.02;
const textMatch=(a,b)=>{const x=norm(a),y=norm(b);return !!x&&!!y&&(x===y||x.includes(y)||y.includes(x))};

export default function FinancialForecast({userId,expenses,income,month,year}){
 const[data,setData]=useState({budget:0,recurring:[],subscriptions:[],purchases:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!userId||!month||!year)return;let alive=true;async function load(){setLoading(true);setError('');const[b,r,s,p]=await Promise.all([
  supabase.from('finance_monthly_budgets').select('valor').eq('user_id',userId).eq('mes',month).eq('ano',year).maybeSingle(),
  supabase.from('finance_recurring').select('id,descricao,valor,dia,last_confirmed_month,ativo').eq('user_id',userId).eq('ativo',true),
  supabase.from('finance_subscriptions').select('id,nome,valor,dia,ativo').eq('user_id',userId).eq('ativo',true),
  supabase.from('credit_card_purchases').select('id,descricao,valor_total,parcelas,data_compra').eq('user_id',userId)
 ]);if(!alive)return;const firstError=b.error||r.error||s.error||p.error;if(firstError)setError(firstError.message);setData({budget:Number(b.data?.valor||0),recurring:r.data||[],subscriptions:s.data||[],purchases:p.data||[]});setLoading(false)}load();return()=>{alive=false}},[userId,month,year]);
 const calc=useMemo(()=>{const total=expenses.reduce((sum,x)=>sum+Number(x.valor||0),0),days=new Date(year,month,0).getDate(),now=new Date(),current=now.getFullYear()===year&&now.getMonth()+1===month,past=new Date(year,month-1,1)<new Date(now.getFullYear(),now.getMonth(),1),future=!current&&!past,elapsed=past?days:current?Math.max(now.getDate(),1):0,remainingDays=past?0:current?Math.max(days-elapsed,0):days,daily=elapsed?total/elapsed:0;const key=`${year}-${String(month).padStart(2,'0')}`,todayDay=current?now.getDate():future?0:days;const matchedExpense=(name,value)=>expenses.some(e=>textMatch(e.descricao,name)&&sameAmount(e.valor,value));const pendingRecurring=past?0:data.recurring.filter(x=>x.last_confirmed_month!==key&&Number(x.dia||1)>todayDay&&!matchedExpense(x.descricao,x.valor)).reduce((s,x)=>s+Number(x.valor||0),0);const pendingSubscriptions=past?[]:data.subscriptions.filter(x=>Number(x.dia||1)>todayDay&&!matchedExpense(x.nome,x.valor));const subscriptionTotal=pendingSubscriptions.reduce((s,x)=>s+Number(x.valor||0),0);const target=monthIndex(year,month);const cardInstallments=past?0:data.purchases.reduce((sum,p)=>{if(!p.data_compra)return sum;const d=new Date(`${p.data_compra}T12:00:00`),start=monthIndex(d.getFullYear(),d.getMonth()+1),n=Math.max(Number(p.parcelas||1),1),installment=Number(p.valor_total||0)/n;if(target<start||target>=start+n||matchedExpense(p.descricao,installment))return sum;return sum+installment},0);const paceFuture=current?daily*remainingDays:0,committed=pendingRecurring+subscriptionTotal+cardInstallments,base=past?total:total+paceFuture+committed,saving=past?total:total+(paceFuture*.9)+committed,allRecurring=past?total:total+paceFuture+subscriptionTotal+cardInstallments+data.recurring.filter(x=>x.last_confirmed_month!==key&&!matchedExpense(x.descricao,x.valor)).reduce((s,x)=>s+Number(x.valor||0),0),limit=data.budget||Number(income||0),balance=Number(income||0)-base,usage=limit?base/limit*100:0,budgetRemaining=data.budget?Math.max(data.budget-total,0):0,remainingPace=current&&remainingDays?Math.max(base-total,0)/remainingDays:0,daysToBurst=data.budget&&remainingPace>0?Math.ceil(budgetRemaining/remainingPace):null,subscriptionPct=income?subscriptionTotal/Number(income)*100:0;return{total,days,elapsed,remainingDays,daily,pendingRecurring,subscriptionTotal,cardInstallments,committed,base,saving,allRecurring,limit,balance,usage,daysToBurst,subscriptionPct,past,current,future}},[expenses,income,month,year,data]);
 if(loading)return <section className="panel forecast"><div className="forecast-loading">Calculando sua previsão financeira...</div></section>;
 const status=calc.balance<0?'critical':calc.usage>100?'warning':'healthy',headline=calc.past?'Mês encerrado':status==='critical'?'Seu mês pode fechar no negativo':status==='warning'?'A projeção passa do limite':'Sua projeção está sob controle';
 return <section className={`panel forecast forecast-${status}`}><div className="forecast-head"><div><span className="forecast-kicker"><Sparkles size={12}/> PREVISÃO FINANCEIRA 2.1</span><h2>{calc.past?'Como este mês terminou':'Como seu mês tende a terminar'}</h2><p>{calc.past?'Valores fechados do período selecionado.':'Combina seu ritmo de gastos com compromissos que ainda não apareceram nos lançamentos.'}</p></div><div className={`forecast-status ${status}`}>{status==='healthy'?<ShieldCheck size={15}/>:<AlertTriangle size={15}/>} {headline}</div></div>{error&&<div className="error banner">{error}</div>}
 <div className="forecast-hero"><div><span>Saldo projetado no fim do mês <CalcInfo title="Saldo projetado">Renda mensal − gasto total projetado. O gasto projetado soma o que já foi lançado, o ritmo médio dos dias restantes e compromissos futuros identificados.</CalcInfo></span><strong className={calc.balance<0?'negative':''}>{money(calc.balance)}</strong><small>com gasto total {calc.past?'registrado':'estimado'} em {money(calc.base)}</small></div><div className="forecast-meter"><div><i style={{width:`${clamp(calc.usage,0,100)}%`}}/></div><span>{calc.limit?`${calc.usage.toFixed(0)}% do ${data.budget?'orçamento':'valor disponível'}`:'Defina renda ou orçamento para comparar'} <CalcInfo title="Percentual usado">Gasto projetado ÷ orçamento mensal. Se não houver orçamento definido, usamos a renda como referência.</CalcInfo></span></div></div>
 <div className="forecast-scenarios"><article><Activity size={17}/><span>{calc.past?'Gasto realizado':'Mantendo o ritmo'} <CalcInfo title="Mantendo o ritmo">Gastos já registrados + média diária atual × dias restantes + compromissos previstos.</CalcInfo></span><b>{money(calc.base)}</b><small>{calc.past?'valor fechado':'cenário mais provável'}</small></article><article><TrendingDown size={17}/><span>{calc.past?'Saldo realizado':'Economizando 10%'} <CalcInfo title="Cenário econômico">Aplica uma redução de 10% somente sobre o ritmo estimado dos próximos dias. Gastos já feitos e compromissos permanecem iguais.</CalcInfo></span><b>{money(calc.past?calc.balance:calc.saving)}</b><small>{calc.past?'renda menos gastos':'sobre o ritmo dos próximos dias'}</small></article><article><Repeat size={17}/><span>{calc.past?'Compromissos pendentes':'Se todas recorrentes ocorrerem'} <CalcInfo title="Cenário conservador">Soma todas as recorrências ainda não confirmadas, além de assinaturas, parcelas e ritmo previsto.</CalcInfo></span><b>{money(calc.past?0:calc.allRecurring)}</b><small>{calc.past?'mês já encerrado':'cenário conservador'}</small></article></div>
 <div className="forecast-commitments"><div><Repeat size={15}/><span>Recorrentes ainda não lançadas <CalcInfo title="Recorrentes pendentes">Somamos recorrências ativas com vencimento ainda pela frente que não aparecem entre os gastos do período.</CalcInfo></span><b>{money(calc.pendingRecurring)}</b></div><div><CalendarClock size={15}/><span>Assinaturas ainda não lançadas <CalcInfo title="Assinaturas pendentes">Assinaturas ativas futuras que ainda não foram encontradas nos lançamentos por descrição e valor.</CalcInfo></span><b>{money(calc.subscriptionTotal)}</b></div><div><CreditCard size={15}/><span>Parcelas ainda não identificadas <CalcInfo title="Parcelas previstas">Para cada compra parcelada, dividimos o valor total pelo número de parcelas e incluímos a parcela correspondente ao mês quando ela ainda não aparece nos gastos.</CalcInfo></span><b>{money(calc.cardInstallments)}</b></div><div className="total"><WalletCards size={15}/><span>Total ainda comprometido <CalcInfo title="Total comprometido">Recorrentes pendentes + assinaturas pendentes + parcelas previstas.</CalcInfo></span><b>{money(calc.committed)}</b></div></div>
 <div className="forecast-alerts">{!calc.past&&data.budget&&calc.base>data.budget&&<div className="danger"><AlertTriangle size={16}/><span>Você pode ultrapassar o orçamento em <b>{money(calc.base-data.budget)}</b>{calc.daysToBurst!==null&&calc.daysToBurst<=calc.remainingDays?` em aproximadamente ${calc.daysToBurst} dias`:''}.</span></div>}{!calc.past&&calc.subscriptionPct>=10&&<div><CalendarClock size={16}/><span>Assinaturas ainda previstas representam <b>{calc.subscriptionPct.toFixed(1)}%</b> da sua renda mensal.</span></div>}{!calc.past&&calc.committed>0&&<div><TrendingUp size={16}/><span>Compromissos ainda não lançados somam <b>{money(calc.committed)}</b>.</span></div>}{status==='healthy'&&!calc.past&&calc.subscriptionPct<10&&<div className="good"><ShieldCheck size={16}/><span>Seu ritmo atual está compatível com o limite considerado.</span></div>}{calc.past&&<div className="good"><ShieldCheck size={16}/><span>Período encerrado: a previsão usa somente os gastos realmente registrados.</span></div>}</div></section>;
}
