import React,{useEffect,useMemo,useState} from 'react';
import {PieChart,BarChart3,Target,TrendingUp,Lightbulb,ShieldAlert} from 'lucide-react';
import {supabase} from '../lib/supabase';
import FinancialEvolution from './FinancialEvolution';
import AdvancedDashboard from './AdvancedDashboard';
import DashboardCharts from './DashboardCharts';
import MonthlyClosing from './MonthlyClosing';
import FinancialForecast from './FinancialForecast';
import CalcInfo from './CalcInfo';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function FinanceInsights({expenses,income,userId,month,year}){
 const[resolvedUserId,setResolvedUserId]=useState(userId||null),[previous,setPrevious]=useState([]);
 useEffect(()=>{let alive=true;if(userId){setResolvedUserId(userId);return()=>{alive=false}}supabase.auth.getUser().then(({data})=>{if(alive)setResolvedUserId(data?.user?.id||null)});return()=>{alive=false}},[userId]);
 const period=useMemo(()=>{if(month&&year)return{month:Number(month),year:Number(year)};const dated=expenses.find(x=>x.data);if(dated){const[y,m]=String(dated.data).split('-').map(Number);if(y&&m)return{month:m,year:y}}const now=new Date();return{month:now.getMonth()+1,year:now.getFullYear()}},[month,year,expenses]);
 useEffect(()=>{if(!resolvedUserId)return;const d=new Date(period.year,period.month-2,1),n=new Date(period.year,period.month-1,1),first=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`,last=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`;supabase.from('gastos').select('valor,categoria,data').eq('user_id',resolvedUserId).gte('data',first).lt('data',last).then(({data})=>setPrevious(data||[]))},[resolvedUserId,period.month,period.year]);
 const categories=useMemo(()=>{const map={};expenses.forEach(e=>{map[e.categoria]=(map[e.categoria]||0)+Number(e.valor||0)});return Object.entries(map).sort((a,b)=>b[1]-a[1])},[expenses]);
 const total=expenses.reduce((s,e)=>s+Number(e.valor||0),0),prevTotal=previous.reduce((s,e)=>s+Number(e.valor||0),0),top=categories[0],average=expenses.length?total/expenses.length:0;
 const smart=useMemo(()=>{const prevMap={};previous.forEach(e=>prevMap[e.categoria]=(prevMap[e.categoria]||0)+Number(e.valor||0));const messages=[];if(prevTotal>0){const delta=total-prevTotal,pct=Math.abs(delta/prevTotal*100);messages.push({tone:delta>0?'warn':'good',title:delta>0?'Gastos acima do mês anterior':'Você está gastando menos',text:`${money(Math.abs(delta))} ${delta>0?'a mais':'a menos'} (${pct.toFixed(0)}%) em relação ao mês anterior.`});const growth=categories.map(([name,value])=>({name,value,prev:prevMap[name]||0,diff:value-(prevMap[name]||0)})).filter(x=>x.prev>0&&x.diff>0).sort((a,b)=>b.diff-a.diff)[0];if(growth)messages.push({tone:'warn',title:`Atenção em ${growth.name}`,text:`Essa categoria aumentou ${money(growth.diff)} em comparação ao mês anterior.`})}if(Number(income)>0){const usage=total/Number(income);messages.push({tone:usage>.85?'warn':'good',title:usage>.85?'Orçamento pressionado':'Renda sob controle',text:`Você utilizou ${(usage*100).toFixed(0)}% da renda e ainda tem ${money(Math.max(Number(income)-total,0))} disponível.`})}if(top&&total)messages.push({tone:'info',title:`${top[0]} lidera seus gastos`,text:`Representa ${(top[1]/total*100).toFixed(0)}% do total do mês (${money(top[1])}).`});return messages.slice(0,4)},[categories,previous,total,prevTotal,income,top]);
 return <>{resolvedUserId&&<><FinancialForecast userId={resolvedUserId} expenses={expenses} income={income} month={period.month} year={period.year}/><MonthlyClosing userId={resolvedUserId} month={period.month} year={period.year}/></>}<DashboardCharts expenses={expenses} income={income}/>{resolvedUserId&&<><AdvancedDashboard userId={resolvedUserId} expenses={expenses} income={income} month={period.month} year={period.year}/><FinancialEvolution userId={resolvedUserId} month={period.month} year={period.year}/></>}
 <section className="panel actionable-insights"><div className="panel-head"><div><h2><Lightbulb size={18}/> Insights que viram ação</h2><p>Comparações reais com seu comportamento financeiro, sem frases genéricas.</p></div></div><div className="actionable-insight-grid">{smart.length?smart.map((item,i)=><article key={i} className={`actionable-insight ${item.tone}`}><div>{item.tone==='warn'?<ShieldAlert size={17}/>:<TrendingUp size={17}/>}</div><span><b>{item.title}</b><small>{item.text}</small></span></article>):<div className="empty compact">Continue registrando seus gastos para liberar comparações inteligentes.</div>}</div></section>
 <section className="insights-grid"><article className="panel insight-card"><div className="panel-head"><div><h2>Onde seu dinheiro está indo <CalcInfo title="Distribuição por categoria">Somamos todos os gastos de cada categoria e dividimos cada total pelo total gasto no mês.</CalcInfo></h2><p>Distribuição dos gastos deste mês.</p></div><PieChart size={20}/></div>{categories.length?<div className="category-bars">{categories.slice(0,6).map(([name,value])=><div className="category-row" key={name}><div><span>{name}</span><b>{money(value)}</b></div><div className="category-track"><i style={{width:`${total?value/total*100:0}%`}}/></div></div>)}</div>:<div className="empty compact">Adicione gastos para ver a distribuição.</div>}</article><article className="panel insight-card"><div className="panel-head"><div><h2>Insights rápidos</h2><p>Uma leitura simples do seu mês.</p></div><TrendingUp size={20}/></div><div className="insight-list"><div><BarChart3 size={17}/><span>Gasto médio por lançamento</span><b>{money(average)}</b></div><div><Target size={17}/><span>Maior categoria</span><b>{top?`${top[0]} · ${money(top[1])}`:'—'}</b></div><div><TrendingUp size={17}/><span>Renda ainda disponível</span><b>{money(Math.max(Number(income||0)-total,0))}</b></div></div></article></section></>;
}