import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,Target,WalletCards} from 'lucide-react';
import MoneyBuckets from './MoneyBuckets';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const keyFor=userId=>`financeiro-goals-${userId}`;

export default function FinanceGoals({userId}){
 const[goals,setGoals]=useState([]),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{try{setGoals(JSON.parse(localStorage.getItem(keyFor(userId))||'[]'))}catch{setGoals([])}},[userId]);
 function persist(next){setGoals(next);localStorage.setItem(keyFor(userId),JSON.stringify(next))}
 function add(e){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),target=Number(f.get('target')),saved=Number(f.get('saved')||0);if(!name||target<=0||saved<0){setError('Preencha os valores corretamente.');setSaving(false);return}persist([{id:crypto.randomUUID(),name,target,saved,createdAt:new Date().toISOString()},...goals]);e.currentTarget.reset();setShow(false);setSaving(false)}
 function updateSaved(id,value){const n=Math.max(0,Number(value)||0);persist(goals.map(g=>g.id===id?{...g,saved:n}:g))}
 function remove(id){persist(goals.filter(g=>g.id!==id))}
 const total=useMemo(()=>goals.reduce((s,g)=>s+Number(g.saved),0),[goals]);
 return <><section className="panel goals-panel"><div className="panel-head"><div><h2><Target size={17} style={{verticalAlign:'-3px',marginRight:7}}/> Metas financeiras</h2><p>Guarde dinheiro para o que você realmente quer.</p></div><button className="secondary" onClick={()=>setShow(true)}><Plus size={15}/> Nova meta</button></div>{goals.length===0?<div className="goal-empty"><WalletCards size={28}/><b>Crie sua primeira meta</b><span>Ex.: celular, viagem, reserva de emergência ou qualquer objetivo.</span></div>:<div className="goals-list">{goals.map(g=>{const pct=Math.min(Number(g.saved)/Number(g.target)*100,100);return <article className="goal" key={g.id}><div className="goal-top"><div><b>{g.name}</b><small>{money(g.saved)} de {money(g.target)}</small></div><button className="delete" onClick={()=>remove(g.id)} title="Excluir meta"><Trash2 size={15}/></button></div><div className="goal-progress"><i style={{width:`${pct}%`}}/></div><div className="goal-bottom"><span>{pct.toFixed(0)}% concluído</span>{pct>=100?<strong>Meta atingida 🎉</strong>:<label>Guardado <input type="number" min="0" step="0.01" value={g.saved} onChange={e=>updateSaved(g.id,e.target.value)}/></label>}</div></article>})}<div className="goals-total"><span>Total guardado nas metas</span><b>{money(total)}</b></div></div>}{show&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="modal" onSubmit={add}><div className="modal-head"><div><h2>Nova meta</h2><p>Defina um objetivo e acompanhe sua evolução.</p></div><button type="button" className="close" onClick={()=>setShow(false)}>×</button></div><label>Nome da meta</label><input name="name" required placeholder="Ex.: Reserva de emergência"/><label>Valor da meta</label><input name="target" type="number" min="0.01" step="0.01" required placeholder="Ex.: 5000"/><label>Quanto já guardou?</label><input name="saved" type="number" min="0" step="0.01" defaultValue="0" placeholder="0,00"/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Salvando...':'Criar meta'}</button></form></div>}</section><MoneyBuckets userId={userId}/></>;
}
