import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,CalendarClock,CreditCard,Repeat,ShieldCheck,Sparkles,TrendingDown,TrendingUp,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {calculateMonthProjection,calculatePendingCommitments} from '../lib/financeEngine';
import CalcInfo from './CalcInfo';
import './FinancialForecast.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const clamp=(v,min,max)=>Math.min(Math.max(v,min),max);

export default function FinancialForecast({userId,expenses,income,month,year}){
 const[data,setData]=useState({budget:0,recurring:[],subscriptions:[],purchases:[],cards:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!userId||!month||!year)return;let alive=true;async function load(){setLoading(true);setError('');const[b,r,s,p,c]=await Promise.all([
  supabase.from('finance_monthly_budgets').select('valor').eq('user_id',userId).eq('mes',month).eq('ano',year).maybeSingle(),
  supabase.from('finance_recurring').select('id,descricao,valor,dia,last_confirmed_month,ativo').eq('user_id',userId).eq('ativo',true),
  supabase.from('finance_subscriptions').select('id,nome,valor,dia,ativo').eq('user_id',userId).eq('ativo',true),
  supabase.from('credit_card_purchases').select('id,card_id,descricao,valor_total,parcelas,data_compra').eq('user_id',userId),
  supabase.from('credit_cards').select('id,nome,dia_fechamento,dia_vencimento').eq('user_id',userId)
 ]);if(!alive)return;const firstError=b.error||r.error||s.error||p.error||c.error;if(firstError)setError(firstError.message);setData({budget:Number(b.data?.valor||0),recurring:r.data||[],subscriptions:s.data||[],purchases:p.data||[],cards:c.data||[]});setLoading(false)}load();return()=>{alive=false}},[userId,month,year]);
 const calc=useMemo(()=>{
  const pending=calculatePendingCommitments({expenses,recurring:data.recurring,subscriptions:data.subscriptions,cards:data.cards,purchases:data.purchases,month,year});
  const projection=calculateMonthProjection({expenses,income,month,year,commitments:pending.totalCommitments});
  const futurePace=Math.max(projection.projected-projection.total,0),base=projection.past?projection.total:projection.projectedWithCommitments,saving=projection.past?projection.total:projection.total+(futurePace*.9)+pending.totalCommitments;
  const limit=data.budget||Number(income||0),balance=Number(income||0)-base,usage=limit?base/limit*100:0,budgetRemaining=data.budget?Math.max(data.budget-projection.total,0):0,remainingPace=projection.current&&projection.remainingDays?Math.max(base-projection.total,0)/projection.remainingDays:0,daysToBurst=data.budget&&remainingPace>0?Math.ceil(budgetRemaining/remainingPace):null,subscriptionPct=income?pending.pendingSubscriptions/Number(income)*100:0;
  return{...projection,pendingRecurring:pending.pendingRecurring,subscriptionTotal:pending.pendingSubscriptions,cardInstallments:pending.pendingCards,committed:pending.totalCommitments,base,saving,allRecurring:base,limit,balance,usage,daysToBurst,subscriptionPct};
 },[expenses,income,month,year,data]);
 if(loading)return <section className="panel forecast"><div className="forecast-loading">Calculando sua previsão financeira...</div></section>;
 const status=calc.balance<0?'critical':calc.usage>100?'warning':'healthy',headline=calc.past?'Mês encerrado':status==='critical'?'Seu mês pode fechar no negativo':status==='warning'?'A projeção passa do limite':'Sua projeção está sob controle';
 return <section className={`panel forecast forecast-${status}`}><div className="forecast-head"><div><span className="forecast-kicker"><Sparkles size={12}/> PREVISÃO FINANCEIRA 3.0</span><h2>{calc.past?'Como este mês terminou':'Como seu mês tende a terminar'}</h2><p>{calc.past?'Valores fechados do período selecionado.':'Usa o mesmo motor financeiro do resumo e das recomendações, incluindo o ciclo real de fechamento dos cartões.'}</p></div><div className={`forecast-status ${status}`}>{status==='healthy'?<ShieldCheck size={15}/>:<AlertTriangle size={15}/>} {headline}</div></div>{error&&<div className="error banner">{error}</div>}
 <div className="forecast-hero"><div><span>Saldo projetado no fim do mês <CalcInfo title="Saldo projetado">Renda mensal − projeção de gastos − compromissos ainda não lançados. Recorrências, assinaturas e parcelas usam a mesma regra em todo o app.</CalcInfo></span><strong className={calc.balance<0?'negative':''}>{money(calc.balance)}</strong><small>com gasto total {calc.past?'registrado':'estimado'} em {money(calc.base)}</small></div><div className="forecast-meter"><div><i style={{width:`${clamp(calc.usage,0,100)}%`}}/></div><span>{calc.limit?`${calc.usage.toFixed(0)}% do ${data.budget?'orçamento':'valor disponível'}`:'Defina renda ou orçamento para comparar'} <CalcInfo title="Percentual usado">Gasto projetado ÷ orçamento mensal. Se não houver orçamento definido, usamos a renda como referência.</CalcInfo></span></div></div>
 <div className="forecast-scenarios"><article><Activity size={17}/><span>{calc.past?'Gasto realizado':'Mantendo o ritmo'} <CalcInfo title="Mantendo o ritmo">Gastos já registrados + projeção pelo ritmo médio diário + compromissos previstos.</CalcInfo></span><b>{money(calc.base)}</b><small>{calc.past?'valor fechado':'cenário mais provável'}</small></article><article><TrendingDown size={17}/><span>{calc.past?'Saldo realizado':'Economizando 10%'} <CalcInfo title="Cenário econômico">Aplica redução de 10% apenas à parte ainda projetada do gasto. Valores já registrados e compromissos conhecidos permanecem.</CalcInfo></span><b>{money(calc.past?calc.balance:calc.saving)}</b><small>{calc.past?'renda menos gastos':'sobre o ritmo dos próximos dias'}</small></article><article><Repeat size={17}/><span>{calc.past?'Compromissos pendentes':'Cenário com compromissos'} <CalcInfo title="Cenário com compromissos">Mantém a projeção e reserva todas as recorrências, assinaturas e parcelas detectadas pelo motor financeiro.</CalcInfo></span><b>{money(calc.past?0:calc.allRecurring)}</b><small>{calc.past?'mês já encerrado':'cenário conservador'}</small></article></div>
 <div className="forecast-commitments"><div><Repeat size={15}/><span>Recorrentes ainda não lançadas <CalcInfo title="Recorrentes pendentes">Recorrências ativas, ainda não confirmadas e que não foram encontradas nos lançamentos por descrição e valor.</CalcInfo></span><b>{money(calc.pendingRecurring)}</b></div><div><CalendarClock size={15}/><span>Assinaturas ainda não lançadas <CalcInfo title="Assinaturas pendentes">Assinaturas ativas que ainda não foram encontradas entre os lançamentos do período.</CalcInfo></span><b>{money(calc.subscriptionTotal)}</b></div><div><CreditCard size={15}/><span>Parcelas ainda não identificadas <CalcInfo title="Parcelas previstas">A parcela entra no mês correto considerando data da compra, dia de fechamento do cartão e quantidade de parcelas.</CalcInfo></span><b>{money(calc.cardInstallments)}</b></div><div className="total"><WalletCards size={15}/><span>Total ainda comprometido <CalcInfo title="Total comprometido">Recorrentes pendentes + assinaturas pendentes + parcelas previstas.</CalcInfo></span><b>{money(calc.committed)}</b></div></div>
 <div className="forecast-alerts">{!calc.past&&data.budget&&calc.base>data.budget&&<div className="danger"><AlertTriangle size={16}/><span>Você pode ultrapassar o orçamento em <b>{money(calc.base-data.budget)}</b>{calc.daysToBurst!==null&&calc.daysToBurst<=calc.remainingDays?` em aproximadamente ${calc.daysToBurst} dias`:''}.</span></div>}{!calc.past&&calc.subscriptionPct>=10&&<div><CalendarClock size={16}/><span>Assinaturas ainda previstas representam <b>{calc.subscriptionPct.toFixed(1)}%</b> da sua renda mensal.</span></div>}{!calc.past&&calc.committed>0&&<div><TrendingUp size={16}/><span>Compromissos ainda não lançados somam <b>{money(calc.committed)}</b>.</span></div>}{status==='healthy'&&!calc.past&&calc.subscriptionPct<10&&<div className="good"><ShieldCheck size={16}/><span>Seu ritmo atual está compatível com o limite considerado.</span></div>}{calc.past&&<div className="good"><ShieldCheck size={16}/><span>Período encerrado: a previsão usa somente os gastos realmente registrados.</span></div>}</div></section>;
}
