import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,PiggyBank,Plus,Sparkles,Target,Trash2,TrendingUp,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import MoneyBuckets from './MoneyBuckets';
import CalcInfo from './CalcInfo';
import './FinanceGoals.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const keyFor=userId=>`financeiro-goals-${userId}`;
const today=()=>new Date(new Date().getFullYear(),new Date().getMonth(),new Date().getDate());
const monthsUntil=date=>{if(!date)return null;const end=new Date(`${date}T12:00:00`),now=today();if(end<now)return 0;return Math.max(1,(end.getFullYear()-now.getFullYear())*12+(end.getMonth()-now.getMonth())+(end.getDate()>=now.getDate()?1:0))};
const daysUntil=date=>{if(!date)return null;return Math.ceil((new Date(`${date}T12:00:00`)-today())/86400000)};

export default function FinanceGoals({userId}){
 const[goals,setGoals]=useState([]),[show,setShow]=useState(false),[depositGoal,setDepositGoal]=useState(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[available,setAvailable]=useState(0);
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(keyFor(userId))||'[]');setGoals((Array.isArray(raw)?raw:[]).map(g=>({...g,deadline:g.deadline||'',createdAt:g.createdAt||new Date().toISOString()})))}catch{setGoals([])}},[userId]);
 useEffect(()=>{let active=true;supabase.from('finance_balances').select('valor').eq('user_id',userId).eq('tipo','disponivel').maybeSingle().then(({data})=>{if(active)setAvailable(Number(data?.valor||0))});return()=>{active=false}},[userId]);
 function persist(next){setGoals(next);localStorage.setItem(keyFor(userId),JSON.stringify(next))}
 function add(e){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget),name=String(f.get('name')).trim(),target=Number(f.get('target')),saved=Number(f.get('saved')||0),deadline=String(f.get('deadline')||'');if(!name||target<=0||saved<0||saved>target){setError('Preencha os valores corretamente.');setSaving(false);return}persist([{id:crypto.randomUUID(),name,target,saved,deadline,createdAt:new Date().toISOString()},...goals]);e.currentTarget.reset();setShow(false);setSaving(false)}
 function remove(id){persist(goals.filter(g=>g.id!==id))}
 async function deposit(e){e.preventDefault();if(!depositGoal)return;setSaving(true);setError('');const f=new FormData(e.currentTarget),amount=Number(f.get('amount')),source=String(f.get('source'));if(!amount||amount<=0){setError('Informe um valor válido.');setSaving(false);return}const remaining=Math.max(Number(depositGoal.target)-Number(depositGoal.saved),0),value=Math.min(amount,remaining);if(source==='disponivel'){const{data:rows,error:loadError}=await supabase.from('finance_balances').select('tipo,valor').eq('user_id',userId).in('tipo',['disponivel','guardado']);if(loadError){setError(loadError.message);setSaving(false);return}const current={disponivel:0,guardado:0,...Object.fromEntries((rows||[]).map(x=>[x.tipo,Number(x.valor)]))};if(current.disponivel<value){setError('Saldo disponível insuficiente para esse aporte.');setSaving(false);return}const nextAvailable=current.disponivel-value,nextSaved=current.guardado+value;const{error:upError}=await supabase.from('finance_balances').upsert([{user_id:userId,tipo:'disponivel',valor:nextAvailable},{user_id:userId,tipo:'guardado',valor:nextSaved}],{onConflict:'user_id,tipo'});if(upError){setError(upError.message);setSaving(false);return}const{error:txError}=await supabase.from('finance_transfers').insert({user_id:userId,de:'disponivel',para:'guardado',valor:value,descricao:`Aporte na meta: ${depositGoal.name}`});if(txError){await supabase.from('finance_balances').upsert([{user_id:userId,tipo:'disponivel',valor:current.disponivel},{user_id:userId,tipo:'guardado',valor:current.guardado}],{onConflict:'user_id,tipo'});setError(txError.message);setSaving(false);return}setAvailable(nextAvailable)}persist(goals.map(g=>g.id===depositGoal.id?{...g,saved:Math.min(Number(g.target),Number(g.saved)+value)}:g));setDepositGoal(null);setSaving(false)}
 const total=useMemo(()=>goals.reduce((s,g)=>s+Number(g.saved),0),[goals]),targetTotal=useMemo(()=>goals.reduce((s,g)=>s+Number(g.target),0),[goals]);
 const activeGoals=goals.filter(g=>Number(g.saved)<Number(g.target)).length,completed=goals.length-activeGoals;
 return <><section className="panel goals-panel goals-2"><div className="panel-head"><div><span className="goals-kicker"><Sparkles size={12}/> METAS 2.0</span><h2><Target size={17}/> Metas financeiras</h2><p>Defina prazos, faça aportes e veja quanto precisa guardar para chegar lá.</p></div><button className="secondary" onClick={()=>setShow(true)}><Plus size={15}/> Nova meta</button></div>
 <div className="goals-overview"><div><PiggyBank size={17}/><span>Total guardado <CalcInfo title="Total guardado">Soma do valor já acumulado em todas as metas cadastradas.</CalcInfo></span><b>{money(total)}</b></div><div><Target size={17}/><span>Objetivo total <CalcInfo title="Objetivo total">Soma do valor-alvo de todas as metas.</CalcInfo></span><b>{money(targetTotal)}</b></div><div><TrendingUp size={17}/><span>Metas em andamento <CalcInfo title="Metas em andamento">Quantidade de metas em que o valor guardado ainda é menor que o objetivo.</CalcInfo></span><b>{activeGoals}</b></div><div><CheckCircle2 size={17}/><span>Concluídas <CalcInfo title="Metas concluídas">Quantidade de metas em que o valor guardado atingiu ou superou o objetivo.</CalcInfo></span><b>{completed}</b></div></div>
 {error&&<div className="error banner">{error}</div>}{goals.length===0?<div className="goal-empty"><WalletCards size={28}/><b>Crie sua primeira meta</b><span>Defina um valor e, se quiser, um prazo para o app calcular o ritmo necessário.</span></div>:<div className="goals-list">{goals.map(g=>{const saved=Number(g.saved||0),target=Number(g.target||0),pct=Math.min(target?saved/target*100:0,100),remaining=Math.max(target-saved,0),months=monthsUntil(g.deadline),days=daysUntil(g.deadline),monthly=months?remaining/months:0,complete=pct>=100,late=!complete&&g.deadline&&days<0;return <article className={`goal goal-2-card ${complete?'complete':''} ${late?'late':''}`} key={g.id}><div className="goal-top"><div><b>{g.name}</b><small>{money(saved)} de {money(target)}</small></div><button className="delete" onClick={()=>remove(g.id)} title="Excluir meta"><Trash2 size={15}/></button></div><div className="goal-progress"><i style={{width:`${pct}%`}}/></div><div className="goal-smart-grid"><div><span>Progresso <CalcInfo title="Progresso">Valor guardado ÷ valor da meta × 100. Limitado visualmente a 100%.</CalcInfo></span><b>{pct.toFixed(0)}%</b></div><div><span>Falta <CalcInfo title="Valor restante">Objetivo da meta − valor já guardado. Nunca fica abaixo de zero.</CalcInfo></span><b>{money(remaining)}</b></div><div><span>Prazo <CalcInfo title="Prazo">Data final escolhida por você para concluir a meta.</CalcInfo></span><b>{g.deadline?new Date(`${g.deadline}T12:00:00`).toLocaleDateString('pt-BR'):'Sem prazo'}</b></div><div><span>Ritmo necessário <CalcInfo title="Ritmo necessário">Valor que falta ÷ quantidade estimada de meses até o prazo. Se o prazo venceu, o app sinaliza atraso.</CalcInfo></span><b>{complete?'Concluída':g.deadline?(late?'Prazo vencido':`${money(monthly)}/mês`):'Defina um prazo'}</b></div></div><div className="goal-bottom goal-actions">{complete?<strong><CheckCircle2 size={14}/> Meta atingida</strong>:<><span className={late?'goal-late':'goal-status'}>{late?<><Clock3 size={13}/> Atrasada</>:g.deadline?<><CalendarDays size={13}/> {days} dias restantes</>:<><CalendarDays size={13}/> Sem prazo definido</>}</span><button className="secondary goal-deposit" onClick={()=>{setError('');setDepositGoal(g)}}><Plus size={13}/> Fazer aporte</button></>}</div></article>})}<div className="goals-total"><span>Total guardado nas metas <CalcInfo title="Total guardado nas metas">Soma do valor guardado de cada meta exibida.</CalcInfo></span><b>{money(total)}</b></div></div>}
 {show&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="modal" onSubmit={add}><div className="modal-head"><div><h2>Nova meta</h2><p>Defina o objetivo e deixe o app calcular seu ritmo.</p></div><button type="button" className="close" onClick={()=>setShow(false)}>×</button></div><label>Nome da meta</label><input name="name" required placeholder="Ex.: Reserva de emergência"/><div className="two"><div><label>Valor da meta</label><input name="target" type="number" min="0.01" step="0.01" required placeholder="5000"/></div><div><label>Quanto já guardou?</label><input name="saved" type="number" min="0" step="0.01" defaultValue="0"/></div></div><label>Prazo final <small>(opcional)</small></label><input name="deadline" type="date" min={new Date().toISOString().slice(0,10)}/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Salvando...':'Criar meta'}</button></form></div>}
 {depositGoal&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setDepositGoal(null)}><form className="modal" onSubmit={deposit}><div className="modal-head"><div><h2>Aporte em {depositGoal.name}</h2><p>Faltam {money(Math.max(Number(depositGoal.target)-Number(depositGoal.saved),0))} para concluir.</p></div><button type="button" className="close" onClick={()=>setDepositGoal(null)}>×</button></div><label>Valor do aporte</label><input name="amount" type="number" min="0.01" step="0.01" max={Math.max(Number(depositGoal.target)-Number(depositGoal.saved),0)} required autoFocus/><label>Origem do dinheiro</label><select name="source" defaultValue="manual"><option value="manual">Aporte manual — só atualiza a meta</option><option value="disponivel">Mover do saldo disponível — {money(available)}</option></select><small className="goal-deposit-note">Ao usar o saldo disponível, o valor é transferido para “Guardado” sem virar gasto.</small>{error&&<div className="error">{error}</div>}<button className="primary" disabled={saving}>{saving?'Aplicando...':'Confirmar aporte'}</button></form></div>}</section><MoneyBuckets userId={userId}/></>;
}
