import React,{useEffect,useMemo,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,CalendarCheck2,ChevronDown,Minus,ReceiptText,Sparkles,TrendingDown,TrendingUp,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import CalcInfo from './CalcInfo';
import './MonthlyClosing.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pct=v=>`${Math.abs(Number(v||0)).toFixed(1)}%`;
const monthName=(y,m)=>new Date(y,m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
const key=(y,m)=>`${y}-${String(m).padStart(2,'0')}`;
const shift=(y,m,delta)=>{const d=new Date(y,m-1+delta,1);return{year:d.getFullYear(),month:d.getMonth()+1}};

export default function MonthlyClosing({userId,month,year}){
 const[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[expanded,setExpanded]=useState(false);
 useEffect(()=>{let alive=true;async function load(){setLoading(true);setError('');const start=shift(year,month,-5),end=shift(year,month,1),from=`${start.year}-${String(start.month).padStart(2,'0')}-01`,to=`${end.year}-${String(end.month).padStart(2,'0')}-01`;const[g,r]=await Promise.all([supabase.from('gastos').select('id,descricao,valor,categoria,data,tipo').eq('user_id',userId).gte('data',from).lt('data',to).order('data'),supabase.from('rendas').select('valor,mes,ano').eq('user_id',userId).gte('ano',start.year).lte('ano',end.year)]);if(!alive)return;if(g.error||r.error){setError(g.error?.message||r.error?.message||'Não foi possível montar o fechamento mensal.');setLoading(false);return}const months=Array.from({length:6},(_,i)=>shift(year,month,i-5));const built=months.map(({year:y,month:m})=>{const mk=key(y,m),rows=(g.data||[]).filter(x=>String(x.data).startsWith(mk)),income=(r.data||[]).filter(x=>Number(x.ano)===y&&Number(x.mes)===m).reduce((s,x)=>s+Number(x.valor||0),0),spent=rows.reduce((s,x)=>s+Number(x.valor||0),0),fixed=rows.filter(x=>x.tipo==='fixo').reduce((s,x)=>s+Number(x.valor||0),0),cats={};rows.forEach(x=>cats[x.categoria]=(cats[x.categoria]||0)+Number(x.valor||0));const topCategory=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0]||null,biggest=[...rows].sort((a,b)=>Number(b.valor)-Number(a.valor))[0]||null;return{year:y,month:m,label:monthName(y,m),income,spent,balance:income-spent,fixed,variable:spent-fixed,count:rows.length,topCategory,biggest,savingsRate:income?((income-spent)/income)*100:0}});setData(built);setLoading(false)}if(userId)load();return()=>{alive=false}},[userId,month,year]);
 const current=data[data.length-1],previous=data[data.length-2];
 const comparison=useMemo(()=>{if(!current||!previous)return null;const spendDelta=previous.spent?((current.spent-previous.spent)/previous.spent)*100:(current.spent?100:0),incomeDelta=previous.income?((current.income-previous.income)/previous.income)*100:(current.income?100:0),balanceDelta=current.balance-previous.balance;return{spendDelta,incomeDelta,balanceDelta}},[current,previous]);
 if(loading)return <section className="panel monthly-closing loading-closing">Montando comparação entre meses...</section>;if(error)return <section className="panel monthly-closing"><div className="error banner">{error}</div></section>;if(!current)return null;
 const good=current.balance>=0,spendUp=(comparison?.spendDelta||0)>0;
 return <section className="panel monthly-closing"><div className="closing-head"><div><span className="closing-kicker"><CalendarCheck2 size={13}/> FECHAMENTO AUTOMÁTICO</span><h2>{current.label}</h2><p>Resumo do mês e comparação automática com {previous?.label||'o mês anterior'}.</p></div><div className={`closing-status ${good?'good':'bad'}`}>{good?<TrendingUp size={15}/>:<TrendingDown size={15}/>} {good?'Mês positivo':'Mês no vermelho'}</div></div>
 <div className="closing-main"><div className="closing-balance"><span>Resultado do mês <CalcInfo title="Resultado do mês">Renda do mês − soma de todos os gastos registrados no período.</CalcInfo></span><b>{money(current.balance)}</b><small>{current.income?`${current.savingsRate.toFixed(1)}% da renda ${current.savingsRate>=0?'preservada':'excedida'}`:'Defina sua renda para calcular taxa de economia'} <CalcInfo title="Taxa de economia">(Renda − gastos) ÷ renda × 100. Valores negativos significam que os gastos ultrapassaram a renda.</CalcInfo></small></div><div className="closing-compare"><div><span>Gastos vs mês anterior <CalcInfo title="Variação dos gastos">(Gastos deste mês − gastos do mês anterior) ÷ gastos do mês anterior × 100.</CalcInfo></span><b className={spendUp?'danger':'positive'}>{comparison?(spendUp?<ArrowUpRight size={15}/>:comparison.spendDelta<0?<ArrowDownRight size={15}/>:<Minus size={15}/>):null}{comparison?pct(comparison.spendDelta):'—'}</b></div><div><span>Renda vs mês anterior <CalcInfo title="Variação da renda">(Renda deste mês − renda anterior) ÷ renda anterior × 100.</CalcInfo></span><b>{comparison?(comparison.incomeDelta>0?<ArrowUpRight size={15}/>:comparison.incomeDelta<0?<ArrowDownRight size={15}/>:<Minus size={15}/>):null}{comparison?pct(comparison.incomeDelta):'—'}</b></div><div><span>Diferença no saldo <CalcInfo title="Diferença no saldo">Saldo deste mês − saldo do mês anterior.</CalcInfo></span><b className={(comparison?.balanceDelta||0)>=0?'positive':'danger'}>{comparison?money(comparison.balanceDelta):'—'}</b></div></div></div>
 <div className="closing-metrics"><div><WalletCards size={16}/><span>Entradas <CalcInfo title="Entradas">Soma das rendas cadastradas para o mês selecionado.</CalcInfo></span><b>{money(current.income)}</b></div><div><ReceiptText size={16}/><span>Gastos <CalcInfo title="Gastos">Soma de todos os lançamentos de despesa do mês.</CalcInfo></span><b>{money(current.spent)}</b></div><div><Sparkles size={16}/><span>Maior categoria <CalcInfo title="Maior categoria">Agrupamos os gastos por categoria e escolhemos aquela com maior soma no período.</CalcInfo></span><b>{current.topCategory?current.topCategory[0]:'—'}</b><small>{current.topCategory?money(current.topCategory[1]):''}</small></div><div><ReceiptText size={16}/><span>Maior gasto <CalcInfo title="Maior gasto">O lançamento individual de maior valor dentro do mês selecionado.</CalcInfo></span><b>{current.biggest?.descricao||'—'}</b><small>{current.biggest?money(current.biggest.valor):''}</small></div></div>
 <button className="closing-toggle" onClick={()=>setExpanded(v=>!v)}>Comparar últimos 6 meses <ChevronDown size={15} className={expanded?'open':''}/></button>{expanded&&<div className="closing-history">{data.map(x=>{const max=Math.max(...data.map(d=>d.spent),1),width=x.spent/max*100;return <div className="closing-month" key={`${x.year}-${x.month}`}><div><b>{x.label}</b><span>{x.count} lançamentos</span></div><div className="closing-bar"><i style={{width:`${width}%`}}/></div><strong>{money(x.spent)}</strong><em className={x.balance>=0?'positive':'danger'}>{money(x.balance)}</em></div>})}</div>}</section>;
}
