import React,{useEffect,useMemo,useState} from 'react';
import {Gauge,Target,Pencil,TrendingUp,CalendarDays,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './MonthlyBudget.css';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function MonthlyBudget({userId,income,expenses,month,year}){
 const[budget,setBudget]=useState(0),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;supabase.from('finance_monthly_budgets').select('valor').eq('user_id',userId).eq('mes',month).eq('ano',year).maybeSingle().then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setBudget(Number(data?.valor||0))});return()=>{alive=false}},[userId,month,year]);
 const total=useMemo(()=>expenses.reduce((s,x)=>s+Number(x.valor||0),0),[expenses]);
 const daysInMonth=new Date(year,month,0).getDate(),today=new Date(),isCurrent=today.getFullYear()===year&&today.getMonth()+1===month,isPast=new Date(year,month-1,1)<new Date(today.getFullYear(),today.getMonth(),1),elapsed=isCurrent?Math.max(today.getDate(),1):isPast?daysInMonth:1,remainingDays=Math.max(daysInMonth-elapsed,0),dailyAvg=elapsed?total/elapsed:0,projection=isPast?total:isCurrent?dailyAvg*daysInMonth:total,limit=budget||income||0,usedPct=limit?total/limit*100:0,projectionPct=limit?projection/limit*100:0,remaining=limit-total,dailyAllowance=remainingDays>0?Math.max(remaining,0)/remainingDays:0;
 const status=!limit?'Defina um orçamento':projectionPct>100?'Risco de estourar o orçamento':usedPct>=85?'Orçamento quase no limite':'Ritmo sob controle';
 async function save(e){e.preventDefault();setSaving(true);setError('');const value=Number(new FormData(e.currentTarget).get('value'));const{data,error}=await supabase.from('finance_monthly_budgets').upsert({user_id:userId,mes:month,ano:year,valor:value,updated_at:new Date().toISOString()},{onConflict:'user_id,mes,ano'}).select().single();setSaving(false);if(error){setError(error.message);return}setBudget(Number(data.valor));setShow(false)}
 return <section className={`panel monthly-budget ${projectionPct>100?'budget-danger':usedPct>=85?'budget-warn':''}`}><div className="budget-head"><div><span className="budget-kicker"><Gauge size={12}/> ORÇAMENTO 2.0</span><h2>Orçamento mensal</h2><p>Controle quanto pode gastar e veja a previsão de fechamento do mês.</p></div><button className="secondary" onClick={()=>setShow(true)}><Pencil size={14}/> {budget?'Editar orçamento':'Definir orçamento'}</button></div>{error&&<div className="error banner">{error}</div>}<div className="budget-hero"><div className="budget-ring" style={{'--budget-pct':`${Math.min(usedPct,100)}%`}}><div><strong>{limit?`${Math.min(usedPct,999).toFixed(0)}%`:'—'}</strong><span>utilizado</span></div></div><div className="budget-main"><span>{status}</span><strong>{limit?money(Math.max(remaining,0)):money(total)}</strong><small>{limit?'ainda disponíveis neste mês':'gastos registrados no mês'}</small><div className="budget-track"><i style={{width:`${Math.min(usedPct,100)}%`}}/></div><div className="budget-meta"><span>Gasto <b>{money(total)}</b></span><span>Orçamento <b>{limit?money(limit):'Não definido'}</b></span></div></div></div><div className="budget-stats"><div><TrendingUp size={16}/><span>Previsão de fechamento</span><b>{money(projection)}</b><small>{limit&&projection>limit?`${money(projection-limit)} acima do orçamento`:'baseada no ritmo atual'}</small></div><div><CalendarDays size={16}/><span>Limite diário sugerido</span><b>{money(dailyAllowance)}</b><small>{remainingDays} dias restantes</small></div><div><WalletCards size={16}/><span>Saldo após projeção</span><b>{money((income||limit)-projection)}</b><small>{income?'considerando sua renda':'considerando o orçamento'}</small></div></div>{show&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="modal" onSubmit={save}><div className="modal-head"><div><h2>Orçamento do mês</h2><p>Defina o máximo que deseja gastar neste mês.</p></div><button type="button" className="close" onClick={()=>setShow(false)}>×</button></div><label>Limite mensal</label><input name="value" type="number" min="0.01" step="0.01" required defaultValue={budget||income||''} placeholder="Ex.: 2500,00"/><button className="primary" disabled={saving}>{saving?'Salvando...':'Salvar orçamento'}</button></form></div>}</section>;
}
