import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,Radio,Tv,CalendarClock,WalletCards,Power,PowerOff} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './SubscriptionsCenter.css';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function SubscriptionsCenter({userId}){
 const[items,setItems]=useState([]),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function load(){const{data,error}=await supabase.from('finance_subscriptions').select('*').eq('user_id',userId).order('ativo',{ascending:false}).order('dia');if(error)setError(error.message);else setItems(data||[])}
 useEffect(()=>{load()},[userId]);
 async function add(e){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const{data,error}=await supabase.from('finance_subscriptions').insert({user_id:userId,nome:String(f.get('name')).trim(),valor:Number(f.get('value')),dia:Number(f.get('day')),categoria:'Assinaturas',ativo:true}).select().single();setSaving(false);if(error){setError(error.message);return}setItems(p=>[...p,data].sort((a,b)=>a.dia-b.dia));setShow(false);e.currentTarget.reset()}
 async function toggle(x){const{data,error}=await supabase.from('finance_subscriptions').update({ativo:!x.ativo}).eq('id',x.id).eq('user_id',userId).select().single();if(error){setError(error.message);return}setItems(p=>p.map(i=>i.id===x.id?data:i))}
 async function remove(id){const{error}=await supabase.from('finance_subscriptions').delete().eq('id',id).eq('user_id',userId);if(error){setError(error.message);return}setItems(p=>p.filter(x=>x.id!==id))}
 const active=items.filter(x=>x.ativo),monthly=useMemo(()=>active.reduce((s,x)=>s+Number(x.valor),0),[items]);
 return <article className="panel subs-center"><div className="subs-head"><div><span className="subs-kicker"><Radio size={12}/> CENTRAL DE ASSINATURAS</span><h2>Assinaturas</h2><p>Tenha clareza do que é cobrado automaticamente todo mês.</p></div><button className="secondary" onClick={()=>setShow(true)}><Plus size={15}/> Assinatura</button></div>{error&&<div className="error banner">{error}</div>}<div className="subs-summary"><div><WalletCards size={18}/><span>Custo mensal</span><b>{money(monthly)}</b></div><div><CalendarClock size={18}/><span>Custo anual estimado</span><b>{money(monthly*12)}</b></div><div><Tv size={18}/><span>Ativas</span><b>{active.length}</b></div></div>{!items.length?<div className="subs-empty"><Radio size={26}/><b>Nenhuma assinatura cadastrada</b><span>Netflix, Spotify, academia, armazenamento e outros serviços entram aqui.</span></div>:<div className="subs-list">{items.map(x=><div className={`subs-item ${!x.ativo?'paused':''}`} key={x.id}><div className="subs-logo">{x.nome.slice(0,1).toUpperCase()}</div><div><b>{x.nome}</b><span>{x.ativo?`Próxima cobrança: dia ${x.dia}`:'Assinatura pausada'}</span></div><strong>{money(x.valor)}<small>/mês</small></strong><button className="subs-toggle" onClick={()=>toggle(x)} title={x.ativo?'Pausar':'Reativar'}>{x.ativo?<PowerOff size={14}/>:<Power size={14}/>}</button><button className="delete" onClick={()=>remove(x.id)}><Trash2 size={14}/></button></div>)}</div>}{show&&<div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="modal" onSubmit={add}><div className="modal-head"><div><h2>Nova assinatura</h2><p>Cadastre um serviço que cobra você periodicamente.</p></div><button type="button" className="close" onClick={()=>setShow(false)}>×</button></div><label>Serviço</label><input name="name" required placeholder="Ex.: Spotify"/><div className="two"><div><label>Valor mensal</label><input name="value" type="number" min="0.01" step="0.01" required/></div><div><label>Dia da cobrança</label><input name="day" type="number" min="1" max="31" defaultValue="1" required/></div></div><button className="primary" disabled={saving}>{saving?'Salvando...':'Adicionar assinatura'}</button></form></div>}</article>;
}
