import React,{useEffect,useMemo,useState} from 'react';
import {Landmark,WalletCards,TrendingUp,CreditCard,ShieldCheck,ArrowUpRight,ArrowDownRight,Database} from 'lucide-react';
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {supabase} from '../lib/supabase';
import CalcInfo from './CalcInfo';
import './WealthDashboard.css';

const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const shiftMonth=(y,m,delta)=>{const d=new Date(y,m-1+delta,1);return{year:d.getFullYear(),month:d.getMonth()+1}};
const monthLabel=(y,m)=>new Date(y,m-1,1).toLocaleDateString('pt-BR',{month:'short'}).replace('.','');

export default function WealthDashboard({userId,month,year}){
 const[data,setData]=useState({balances:[],cards:[],purchases:[],snapshots:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[snapshotReady,setSnapshotReady]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);setError('');const start=shiftMonth(year,month,-11),next=shiftMonth(year,month,1),last=`${next.year}-${String(next.month).padStart(2,'0')}-01`;const[b,c,p,s]=await Promise.all([supabase.from('finance_balances').select('tipo,valor').eq('user_id',userId),supabase.from('credit_cards').select('id,nome,apelido,limite').eq('user_id',userId),supabase.from('credit_card_purchases').select('id,card_id,descricao,valor_total,parcelas,data_compra').eq('user_id',userId).lt('data_compra',last),supabase.from('finance_wealth_snapshots').select('ano,mes,disponivel,guardado,investimentos,ativos,divida_cartoes,patrimonio_liquido,limite_cartoes,captured_at').eq('user_id',userId).gte('ano',start.year).lte('ano',year).order('ano',{ascending:true}).order('mes',{ascending:true})]);if(!alive)return;const err=b.error||c.error||p.error;if(err)setError(err.message);const snapshotsUnavailable=Boolean(s.error);setSnapshotReady(!snapshotsUnavailable);setData({balances:b.data||[],cards:c.data||[],purchases:p.data||[],snapshots:s.data||[]});setLoading(false)})().catch(e=>{if(alive){setError(e.message||'Não foi possível carregar o patrimônio.');setLoading(false)}});return()=>{alive=false}},[userId,month,year]);
 const calc=useMemo(()=>{const balances=Object.fromEntries(data.balances.map(x=>[x.tipo,Number(x.valor||0)])),available=balances.disponivel||0,saved=balances.guardado||0,investments=balances.investimentos||0,assets=available+saved+investments;const liabilityFor=(y,m)=>data.purchases.reduce((sum,p)=>{const date=new Date(`${p.data_compra}T12:00:00`),py=date.getFullYear(),pm=date.getMonth()+1,offset=(y-py)*12+(m-pm),parts=Math.max(1,Number(p.parcelas||1));return offset>=0&&offset<parts?sum+Number(p.valor_total||0)/parts:sum},0);const cardDebt=liabilityFor(year,month),net=assets-cardDebt,totalLimit=data.cards.reduce((s,c)=>s+Number(c.limite||0),0),availableLimit=Math.max(0,totalLimit-cardDebt);const points=data.snapshots.filter(x=>{const n=Number(x.ano)*12+Number(x.mes),min=shiftMonth(year,month,-11);return n>=min.year*12+min.month&&n<=year*12+month}).map(x=>({y:Number(x.ano),m:Number(x.mes),label:monthLabel(Number(x.ano),Number(x.mes)),value:Number(x.patrimonio_liquido||0),real:true}));const selectedIndex=points.findIndex(x=>x.y===year&&x.m===month);if(selectedIndex>=0)points[selectedIndex]={...points[selectedIndex],value:net};else points.push({y:year,m:month,label:monthLabel(year,month),value:net,real:false});points.sort((a,b)=>(a.y*12+a.m)-(b.y*12+b.m));const history=points.slice(-6),prev=history.at(-2)?.value??net,variation=net-prev,variationPct=Math.abs(prev)>0?variation/Math.abs(prev)*100:0,allocation=[['Disponível',available],['Guardado',saved],['Investimentos',investments],['Fatura estimada',cardDebt]];return{available,saved,investments,assets,cardDebt,net,totalLimit,availableLimit,history,variation,variationPct,allocation}},[data,month,year]);
 useEffect(()=>{if(loading||!snapshotReady||!userId)return;const now=new Date(),currentMonth=now.getMonth()+1,currentYear=now.getFullYear();if(month!==currentMonth||year!==currentYear)return;const payload={user_id:userId,ano:year,mes:month,disponivel:calc.available,guardado:calc.saved,investimentos:calc.investments,ativos:calc.assets,divida_cartoes:calc.cardDebt,patrimonio_liquido:calc.net,limite_cartoes:calc.totalLimit,captured_at:new Date().toISOString()};supabase.from('finance_wealth_snapshots').upsert(payload,{onConflict:'user_id,ano,mes'}).then(({error})=>{if(error)setSnapshotReady(false);else setData(p=>({...p,snapshots:[...p.snapshots.filter(x=>!(Number(x.ano)===year&&Number(x.mes)===month)),payload]}))})},[loading,snapshotReady,userId,month,year,calc.available,calc.saved,calc.investments,calc.assets,calc.cardDebt,calc.net,calc.totalLimit]);
 if(loading)return <section className="wealth-panel panel"><div className="wealth-loading">Calculando patrimônio...</div></section>;
 return <section className="wealth-panel panel"><div className="panel-head wealth-head"><div><span className="wealth-kicker">PATRIMÔNIO 2.0</span><h2><Landmark size={17}/> Dashboard de patrimônio</h2><p>Ativos, compromissos no cartão e patrimônio líquido em uma única visão.</p></div><div className={`wealth-trend ${calc.variation>=0?'up':'down'}`}>{calc.variation>=0?<ArrowUpRight size={15}/>:<ArrowDownRight size={15}/>} {calc.variationPct.toFixed(1)}% <CalcInfo title="Variação do patrimônio">(Patrimônio atual − patrimônio do snapshot anterior) ÷ valor absoluto do patrimônio anterior × 100.</CalcInfo></div></div>{error&&<div className="error banner">{error}</div>}
 <div className="wealth-hero"><div><span>Patrimônio líquido estimado <CalcInfo title="Patrimônio líquido">Saldo disponível + guardado + investimentos − fatura estimada dos cartões.</CalcInfo></span><strong>{money(calc.net)}</strong><small>Ativos {money(calc.assets)} − fatura estimada {money(calc.cardDebt)}</small></div><div className="wealth-score"><ShieldCheck size={18}/><span>{calc.net>=0?'Patrimônio positivo':'Atenção ao endividamento'}</span></div></div>
 <div className="wealth-stats"><article><WalletCards size={16}/><span>Disponível <CalcInfo title="Disponível">Valor salvo no saldo disponível em Contas/Carteiras.</CalcInfo></span><b>{money(calc.available)}</b></article><article><Landmark size={16}/><span>Guardado <CalcInfo title="Guardado">Valor acumulado no saldo do tipo Guardado.</CalcInfo></span><b>{money(calc.saved)}</b></article><article><TrendingUp size={16}/><span>Investimentos <CalcInfo title="Investimentos">Valor cadastrado no saldo de investimentos.</CalcInfo></span><b>{money(calc.investments)}</b></article><article><CreditCard size={16}/><span>Fatura estimada <CalcInfo title="Fatura estimada">Somamos a parcela correspondente ao mês de cada compra parcelada ativa. Compra à vista conta integralmente no mês da compra.</CalcInfo></span><b>{money(calc.cardDebt)}</b></article></div>
 <div className="wealth-grid"><div className="wealth-chart"><div className="wealth-section-title"><b>Evolução do patrimônio <CalcInfo title="Evolução do patrimônio">Usa snapshots mensais salvos pelo app. O mês selecionado é recalculado com os valores atuais.</CalcInfo></b><span>{snapshotReady?'snapshots mensais reais':'modo estimado'}</span></div><ResponsiveContainer width="100%" height={205}><AreaChart data={calc.history} margin={{top:12,right:8,left:-18,bottom:0}}><defs><linearGradient id="wealthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".24"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:9}} tickFormatter={v=>`${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)} labelFormatter={l=>String(l).toUpperCase()} contentStyle={{background:'#0c121c',border:'1px solid #263044',borderRadius:10,fontSize:11}}/><Area type="monotone" dataKey="value" stroke="currentColor" strokeWidth={2} fill="url(#wealthFill)"/></AreaChart></ResponsiveContainer><small className="wealth-note"><Database size={12}/>{snapshotReady?' O app salva automaticamente um snapshot do patrimônio no mês atual. O histórico ficará cada vez mais preciso com o uso.':' Execute a migration de wealth snapshots no Supabase para ativar o histórico real.'}</small></div>
 <div className="wealth-allocation"><div className="wealth-section-title"><b>Composição <CalcInfo title="Composição">Cada barra compara o valor da categoria com ativos + fatura estimada, usando essa soma como base visual.</CalcInfo></b><span>distribuição atual</span></div>{calc.allocation.map(([label,value])=>{const base=Math.max(calc.assets+calc.cardDebt,1),pct=Math.min(100,Math.max(0,value/base*100));return <div className="wealth-row" key={label}><div><span>{label}</span><b>{money(value)}</b></div><div className="wealth-track"><i style={{width:`${pct}%`}}/></div></div>})}<div className="wealth-limit"><span>Limite disponível nos cartões <CalcInfo title="Limite disponível">Soma dos limites de todos os cartões − fatura estimada do mês. Nunca exibimos valor abaixo de zero.</CalcInfo></span><b>{money(calc.availableLimit)}</b><small>de {money(calc.totalLimit)} em limite total</small></div></div></div></section>;
}
