-- Admin 2.0 audit log
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid null references auth.users(id) on delete set null,
  action text not null,
  target_user_id uuid null references auth.users(id) on delete set null,
  target_email text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs(created_at desc);
create index if not exists admin_audit_logs_actor_idx on public.admin_audit_logs(actor_id);
create index if not exists admin_audit_logs_target_idx on public.admin_audit_logs(target_user_id);

alter table public.admin_audit_logs enable row level security;

create policy "admins can read audit logs"
on public.admin_audit_logs for select
to authenticated
using (public.is_app_admin(auth.uid()));

-- Inserts are intentionally performed only by the server using service_role.
